Chainweb Client
kommitters/kadena.ex pull request #104
Opened 2022-10-22 18:06 UTC by santiagoboterokommit

## Description

Fixes #59 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [ ] This change requires a documentation update

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-10-24 16:06 UTC, juanhurtado10 requested changes

2022-10-24 16:06 UTC, juanhurtado10 commented on lib/chainweb/client/default.ex
> +    base_url = Network.base_url() |> String.replace("{chain_id}", chain_id)
@santiagoboterokommit I'm not sure about the logic behind this code block. Why not just pass the `chain_id` as a parameter?

2022-10-24 16:06 UTC, juanhurtado10 commented on lib/chainweb/client.ex
> +  def request(method, path, chain_id \\ "0", headers \\ [], body \\ "", opts \\ []),
@santiagoboterokommit IMO, the client should not manage the `chain_id`, this is something that should be contained in the request path .... in other words, the API endpoints are responsible for handling it

2022-10-24 16:06 UTC, juanhurtado10 commented on lib/chainweb/util/network.ex
> +defmodule Kadena.Chainweb.Network do
@santiagoboterokommit Are you sure this code will allow users to move between networks without changing environment variables?. Are you anticipating that?

2022-10-24 22:44 UTC, juanhurtado10 requested changes

2022-10-24 22:44 UTC, juanhurtado10 commented on lib/chainweb/util/network.ex
> +defmodule Kadena.Chainweb.Network do
@santiagoboterokommit please, remove this module since it is not related to the HTTP client impl.

2022-10-24 23:28 UTC, juanhurtado10 requested changes

2022-10-24 23:28 UTC, juanhurtado10 commented on test/support/fixtures/chainweb/200.json
> +}
@santiagoboterokommit Please, fix the file indentation.

2022-10-24 23:37 UTC, juanhurtado10 approved these changes

2022-10-25 00:30 UTC, einerzg commented on lib/chainweb/client/default.ex
> +    do: {:error, [chainweb: body]}
@santiagoboterokommit, It's not necessary to add this line here `decoded_body = json_library().decode!(body, keys: :atoms)`

2022-10-25 00:33 UTC, einerzg approved these changes

2022-10-25 13:03 UTC, merged