pact interface #105
kommitters/kadena.ex pull request #110
Opened 2022-10-26 01:00 UTC by EdwinGuayacan

## Description

Fixes # (105)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [ ] This change requires a documentation update

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2022-10-26 20:08 UTC, einerzg requested changes

2022-10-26 20:08 UTC, einerzg commented on test/pact/pact_test.exs
> +    test "with a valid decimal" do
@EdwinGuayacan, `with an invalid integer`?

2022-10-27 15:24 UTC, santiagoboterokommit approved these changes

2022-10-27 17:04 UTC, einerzg approved these changes

2022-10-27 21:43 UTC, merged