123 Poll request body json protocol
kommitters/kadena.ex pull request #128
Opened 2022-11-07 21:08 UTC by SergioGueruiz

Fixes #123 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [ ] This change requires a documentation update

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-11-07 23:07 UTC, santiagoboterokommit requested changes

2022-11-07 23:07 UTC, boterop commented on lib/types/poll_request_body.ex
> +      Base64UrlsList,
it is imported in the top of the struct, you should remove this one

2022-11-07 23:07 UTC, santiagoboterokommit commented on lib/types/poll_request_body.ex
> +      with {:ok, key_list} <- extract_keys(key_list) do
IMO this `with case` is unnecessary

2022-11-07 23:07 UTC, santiagoboterokommit commented on lib/types/poll_request_body.ex
> +    defp extract_keys(%Base64UrlsList{urls: list}) do
you could return in the `extract_keys` function the list without the :ok

2022-11-08 13:59 UTC, santiagoboterokommit requested changes

2022-11-08 13:59 UTC, boterop commented on lib/types/poll_request_body.ex
> +      %{request_keys: extract_keys(key_list)}
IMO could be better if the extract_keys is assigned to a variable, or in other pipe

2022-11-08 13:59 UTC, santiagoboterokommit commented on lib/types/poll_request_body.ex
> +    defp extract_keys(%Base64UrlsList{urls: list}) do
this code is just one line. please use `, do: `

2022-11-08 14:45 UTC, santiagoboterokommit approved these changes

2022-11-08 15:03 UTC, einerzg approved these changes

2022-11-08 16:10 UTC, merged