Prepare release v0.9.0
kommitters/kadena.ex pull request #151
Opened 2022-12-02 19:59 UTC by Odraxs

This pull request includes updated execution and continuation command

2022-12-02 20:01 UTC, juanhurtado10 requested changes

2022-12-02 20:01 UTC, juanhurtado10 commented on README.md
> +     Kadena.Pact.ContCommand.new()
@Odraxs please fix the indentation

2022-12-02 20:03 UTC, juanhurtado10 commented on README.md
> +### Continuation Command
@Odraxs The documents are incomplete, please complete them with examples of each use case. As a user it is not clear to me how to build a command

2022-12-06 14:26 UTC, miguelnietoa requested changes

2022-12-06 14:26 UTC, miguelnietoa commented on README.md
> +  ]
@Odraxs @EdwinGuayacan please fix the indentation

2022-12-06 14:26 UTC, miguelnietoa commented on README.md
> +The step is an Integer of the mutli-step transaction.
@Odraxs @EdwinGuayacan there is a typo here "mutli-step"

2022-12-06 14:26 UTC, miguelnietoa commented on CHANGELOG.md
> +## 0.9.0 (02.12.2022)
@Odraxs @EdwinGuayacan please change the date

2022-12-06 15:07 UTC, juanhurtado10 approved these changes

2022-12-06 15:07 UTC, merged