SPV endpoint implementation
kommitters/kadena.ex pull request #189
Opened 2022-12-23 21:56 UTC by EdwinGuayacan

## Description
It was necessary to modify the `Kadena.Chainweb.Network` module to add a new pattern match for the `base_url/1` function, since the SPV endpoint URL is different from the others.

Fixes #103 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [ ] This change requires a documentation update

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-12-23 22:26 UTC, L-Zuluaga submitted a review, later dismissed
LGTM, let's wait for Miguel's feedback

2022-12-23 23:02 UTC, miguelnietoa requested changes
@EdwinGuayacan Awesome!! 🚀  Some comments added

2022-12-23 23:02 UTC, miguelnietoa commented on lib/chainweb/pact/spv.ex
> +  @type payload_opts :: list()
@EdwinGuayacan IMO we could be more precise in the type definition.

```elixir
@type payload :: [request_key: String.t(), target_chain_id: String.t()]
```

2022-12-23 23:02 UTC, miguelnietoa commented on lib/chainweb/pact/spec.ex
> +  @type data :: list(Command.t()) | Command.t() | list(String.t()) | String.t() | list()
@EdwinGuayacan Keyword list instead!

2022-12-23 23:02 UTC, miguelnietoa commented on README.md
> +Chainweb.Pact.spv(payload_opts, network_id: :testnet04, chain_id: 1)
@EdwinGuayacan Since this endpoint is used for cross-chain transfers, the target chain id of the payload and the chain id of the network options should be different

2022-12-23 23:02 UTC, miguelnietoa commented on README.md
> +   response:
@EdwinGuayacan Small tweak: Can we switch from `response` to `proof` in the SPVResponse module?

2022-12-26 15:33 UTC, juanhurtado10 approved these changes

2022-12-26 15:35 UTC, miguelnietoa approved these changes

2022-12-26 15:37 UTC, merged