Add minor README improvements
kommitters/kadena.ex pull request #71
Opened 2022-10-10 23:11 UTC by miguelnietoa

## Description

Related to #50 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [x] This change requires a documentation update

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-10-10 23:16 UTC, santiagoboterokommit submitted a review, later dismissed

2022-10-10 23:23 UTC, juanhurtado10 requested changes

2022-10-10 23:23 UTC, juanhurtado10 commented on README.md
> +**Kadena.ex** is an Open-Source library for Elixir that allows developers to interact with Kadena, Chainweb, and PACT.
@miguelnietoa my suggestion: `**Kadena.ex** is an open source library for Elixir that allows developers to interact with the Kadena Chainweb.`

2022-10-10 23:23 UTC, juanhurtado10 commented on README.md
> +* Interact with public network endpoints:
@miguelnietoa those "public network endpoints" are actually known as p2p endpoints

2022-10-10 23:23 UTC, juanhurtado10 commented on README.md
> +## Want to jump in?
@miguelnietoa please, reference the contributing guide as well

2022-10-11 14:23 UTC, juanhurtado10 submitted a review, later dismissed

2022-10-11 14:28 UTC, juanhurtado10 approved these changes

2022-10-11 14:30 UTC, merged